// Before publishing your new repository:
// 1. Write the readme file
// 2. Update the issues link in Contributing section in the readme file
// 3. Update the discussion link in config.yml file in .github/ISSUE_TEMPLATE directory

= pth_15 - DPL translator interface library for Teragrep

// Add a short description of your project. Tell what your project does and what it's used for.

This library contains the necessary interfaces to run the pth_10 DPL translator component in the DPL interpreter
without being a direct dependency.

== Features

// List your project's features
* DPLExecutor interface, which should be implemented in the pth_10 component.
* DPLExecutorFactory, that can be used to load the implementation class without a direct Maven dependency.
* DPLExecutorResult interface, which contains the result of the DPLExecutor. Should be implemented in the pth_10 component.

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to compile

// add instructions how people can start to use your project
[source,bash]
----
$ mvn clean package
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
